version: '3.7'
services:
  #client container
  client:
    container_name: nosh_client
    build: ./client
    ports:
      - '3000:3000'
    networks: 
      - nosh
    depends_on:
      - backend
  
  #backend container
  backend:
    container_name: nosh_backend
    build: ./backend
    ports:
      - '5000:5000'
    networks: 
      - nosh
    depends_on:
      - mongo
  
#db container
  mongo:
    container_name: nosh_mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/var/lib/shared/mongodata
    networks: 
      - nosh

volumes:
  mongodata:

networks:
  nosh:
    driver: "bridge"