version: '3.7'
services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - yolo-volume:/var/lib/shared/yolo
    depends_on:
      - backend
    networks: 
      - backends
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - yolo-volume:/var/lib/shared/yolo
    depends_on:
      - mongo
    networks: 
      - backends
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - yolo-volume:/var/lib/shared/yolo
volumes:
  yolo-volume:
networks:
  backends:
    driver: "bridge"